---
# source: https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md

  - name: Install dnsmasq and hostapd
    apt:
      name: "{{item}}"
      update_cache: yes
    with_items:
      - dnsmasq
      - hostapd
      - whois

  - name: Stop the dnsmasq and hostapd service
    service:
      name: "{{item}}"
      state: stopped
      enabled: yes
    with_items:
      - dnsmasq
      - hostapd

  - name: Download hostapd.conf
    get_url:
      url: "{{wifi_hotspot_hostapd_conf_url}}"
      dest: /etc/hostapd/hostapd.conf
      force: yes

  - name: Set DAEMON_CONF in /etc/default/hostapd
    shell: echo DAEMON_CONF=/etc/hostapd/hostapd.conf >> /etc/default/hostapd

  - name: Download dhcpcd.conf
    get_url:
      url: "{{wifi_hotspot_dhcpcd_conf_url}}"
      dest: /etc/dhcpcd.conf
      force: yes

  - name: Download dnsmasq.conf
    get_url:
      url: "{{wifi_hotspot_dnsmasq_conf_url}}"
      dest: /etc/dnsmasq.conf
      force: yes

  - name: Restart the dnsmasq, hostapd and dhcpcd service
    service:
      name: "{{item}}"
      state: restarted
      enabled: yes
    with_items:
      - dnsmasq
      - hostapd
      - dhcpcd

  - name: Configure NAT in iptables (1 of 3)
    shell: iptables --table nat --append POSTROUTING --out-interface eth0 --jump MASQUERADE
  - name: Configure NAT in iptables (2 of 3)
    shell: iptables --append FORWARD --in-interface eth0 --out-interface wlan0 --match state --state RELATED,ESTABLISHED --jump ACCEPT
  - name: Configure NAT in iptables (3 of 3)
    shell: iptables --append FORWARD --in-interface wlan0 --out-interface eth0 --jump ACCEPT

  - name: Export iptables
    shell: iptables-save > /etc/iptables.ipv4.nat

  - name: Enable ipv4 forward in /etc/sysctl.conf
    lineinfile:
      dest: /etc/sysctl.conf
      line: 'net.ipv4.ip_forward=1'

  - name: Enable ipv4 forward in /proc/sys/net/ipv4/ip_forward
    shell: echo 1 > /proc/sys/net/ipv4/ip_forward

  - name: Load the iptables NAT config on boot
    lineinfile:
      dest: /etc/rc.local
      line: 'iptables-restore < /etc/iptables.ipv4.nat'
      insertbefore: 'exit 0'

#  - name: Restart {{wlan_interface}} network interface
#    shell: "wpa_cli terminate ; sleep 2 ; wpa_supplicant -B -i {{wlan_interface}} -c /etc/wpa_supplicant/wpa_supplicant.conf"
