---
  - name: Install (apt-get) QR Scanner Dependencies
    apt:
      name: "{{item}}"
      update_cache: yes
    with_items:
      - python3-pip
      - python3-numpy
      - python3-scipy
      - ipython
      - libzbar0
      - libatlas-base-dev
      - libjasper-dev
      - libqtgui4
      - python3-pyqt5
      - libqt4-test
      - jq

  - name: Install (pip3) QR Scanner Dependencies
    pip:
      name: "{{item}}"
      executable: pip3
    with_items:
      - opencv-python
      - imutils
      - pyzbar
      - jsonmerge


  - name: Download qrscanner_closestdevice.sh
    get_url:
      url: "{{qrscanner_closestdevice}}"
      dest: /qrscanner_closestdevice.sh
      force: yes

  - name: Make qrscanner_closestdevice.sh executable
    shell: chmod +x /qrscanner_closestdevice.sh

  - name: Download upload_scanned_devices.sh
    get_url:
      url: "{{upload_scanned_devices}}"
      dest: /upload_scanned_devices.sh
      force: yes

  - name: Make upload_scanned_devices.sh executable
    shell: chmod +x /upload_scanned_devices.sh

  - name: Download qrscanner.py
    get_url:
      url: "{{qrscanner_python_url}}"
      dest: /qrscanner.py
      force: yes

  - name: Download qrscanner.desktop to autostart
    get_url:
      url: "{{qrscanner_desktop_url}}"
      dest: /etc/xdg/autostart/qrscanner.desktop
      force: yes

  - name: Download qrscanner.desktop to user desktop
    get_url:
      url: "{{qrscanner_desktop_url}}"
      dest: /home/pi/Desktop/qrscanner.desktop
      force: yes
