---
  - name: Clone webcam capture docker repository
    git:
      repo: https://github.com/mkieboom/raspberrypi-webcam-capture-docker
      dest: ~/raspberrypi-webcam-capture-docker/

  - name: Build the Docker image
    docker_image:
      path: ~/raspberrypi-webcam-capture-docker/
      name: mkieboom/raspberrypi-webcam-capture-docker

  - name: Launch the webcam capture docker container
    docker_container:
      image: mkieboom/raspberrypi-webcam-capture-docker
      restart_policy: always
      restart_retries: 3
      state: present
      recreate: yes
      devices:
        - "/dev/video0:/dev/video0"
      volumes:
        - "/tmp/webcam:/tmp/webcam"
