- name: Install software
  hosts: all
  vars:
     vpn_ovpn_config: "{{ lookup('file', '{{vpn_ovpn_config_file}}') }}"
  roles:
#    - config-bluetooth   # only for Raspbian release prior to 'Stretch'
    - install-ssh-server
    - install-vnc-server
    - config-base
#    - install-docker
#    - install-openvpn-server
    - install-openvpn-client
#    - config-wifi-client    # config wifi as the last step as it will restart the wlan interface potentially dropping the connection
    - config-wifi-hotspot
    - install-vpnc-client
    - mapr-retail-demo-qrscanner
    - mapr-retail-demo-connecteddevices
