- name: Install software
  hosts: all
  roles:
#    - config-bluetooth   # only for Raspbian release prior to 'Stretch'
    - config-base
    - install-docker
#    - install-wordpress
#    - install-openvpn-server
    - install-openvpn-client
    - docker-webcam-capture
#    - docker-webcam-stream
#    - docker-streamsets-edge
    - config-wifi        # config wifi as the last step as it will restart the wlan interface potentially dropping the connection
