- name: Install software
  hosts: all
  roles:
#    - config-bluetooth   # only for Raspbian release prior to 'Stretch'
    - config-base
    - config-wifi
    - install-docker
#    - install-wordpress
#    - install-openvpn
    - docker-webcam-capture
#    - docker-streamsets-edge
