---

# Doc: https://www.e-tinkers.com/2016/11/hosting-wordpress-on-raspberry-pi-part-2-install-nginx-php-and-mariadb/

  - name: Run "apt-get update"
    apt: update_cache=yes

  - name: Install Nginx
    apt: name=nginx state=present

  - name: Install PHP
    apt: name={{item}} state=present
    with_items:
         - php5-fpm
         - php5-mysqlnd
         - php5-xmlrpc
         - php5-curl
         - php5-gd
         - php5-imagick
         - php5-imap
         - php5-mcrypt

  - name: Configure Nginx to support .php files
    shell: "sed -ie 's|index index.html index.htm index.nginx-debian.html;|index index.php index.html index.htm index.nginx-debian.html;|g' /etc/nginx/sites-available/default"

  - name: Configure PHP in Nginx
    blockinfile:
      path: /etc/nginx/sites-available/default
      insertafter: "pass the PHP scripts to FastCGI server listening"
      content: |
        location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        }

  - name: Install MariaDB
    apt: name={{item}} state=present
    with_items:
         - mariadb-server
         - mariadb-client

  - name: Download Wordpress
    get_url:
      url: "http://wordpress.org/latest.tar.gz"
      dest: "/tmp/wordpress.tar.gz"

  - name: Extract Wordpress
    unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/html/ copy=no


  - name: Move Wordpress files to webserver root 
    shell: "mv /var/www/html/wordpress/* /var/www/html/."
    register: mv_wordpress_result
    failed_when: "mv_wordpress_result|failed and 'Directory not empty' not in command_result.msg"
    ignore_errors: yes

  - name: PHP runs under 'www-data' user. Open Wordpress to allow updating and installing plugins without FTP. 
    shell: "chown -hR www-data:www-data /var/www/html/"
    # Alternative: add: define(‘FS_METHOD’,’direct’); to /var/www/html/wp-config.php. Didn't work for me.

  - name: Create Wordpress database in MariaDB
    shell: "echo 'create database wordpress' | mysql -u 'root' --password=''"
    register: create_wordpress_database_result
    failed_when: "create_wordpress_database_result|failed and 'database exists' not in command_result.msg"
    ignore_errors: yes

  - name: Grant usage on Wordpress database in MariaDB
    shell: "echo \"grant usage on *.* to root@localhost identified by ''\" | mysql -u 'root' --password=''"

  - name: Grant privileges on Wordpress database in MariaDB
    shell: "echo \"grant all privileges on wordpress.* to root@localhost;\" | mysql -u 'root' --password=''"



