---

# Doc: https://www.e-tinkers.com/2016/11/hosting-wordpress-on-raspberry-pi-part-2-install-nginx-php-and-mariadb/

  - name: Run "apt-get update"
    apt: update_cache=yes

  - name: Install Nginx
    apt: name=nginx state=present

  - name: Install PHP
    apt: name={{item}} state=present
    with_items:
         - php5-fpm
         - php5-mysqlnd
         - php5-xmlrpc
         - php5-curl
         - php5-gd
         - php5-imagick
         - php5-imap
         - php5-mcrypt

  - name: Install MariaDB
    apt: name={{item}} state=present
    with_items:
         - mariadb-server
         - mariadb-client

  - name: Download Wordpress
    get_url:
      url: "http://wordpress.org/latest.tar.gz"
      dest: "/tmp/wordpress.tar.gz"

  - name: Extract Wordpress
    unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/html/ copy=no


