---
  - name: Purge Bluez
    apt: name=bluez state=absent

  - name: Run "apt-get update"
    apt: update_cache=yes

  - name: Install list of packages
    apt: name={{item}} state=present
    with_items:
         - git
         - bc
         - libusb-dev
         - libdbus-1-dev
         - libglib2.0-dev
         - libudev-dev
         - libical-dev
         - libreadline-dev
         - libbluetooth-dev

  - name: Download Bluez
    get_url:
      url: "http://www.kernel.org/pub/linux/bluetooth/bluez-5.41.tar.xz"
      dest: "/tmp/bluez-5.41.tar.xz"

  - name: Extract Bluez
    unarchive: src=/tmp/bluez-5.41.tar.xz dest=/tmp/ copy=no

  - name: Download Bluez patch for Raspberry PI
    get_url:
      url: "https://gist.github.com/pelwell/c8230c48ea24698527cd/archive/3b07a1eb296862da889609a84f8e10b299b7442d.zip"
      dest: "/tmp/3b07a1eb296862da889609a84f8e10b299b7442d.zip"

  - name: Extract Bluez patch for Raspberry PI
    unarchive: src=/tmp/3b07a1eb296862da889609a84f8e10b299b7442d.zip dest=/tmp/bluez-5.41/ copy=no

  - name: Apply Bluez patch
    shell: "git apply -v c8230c48ea24698527cd-3b07a1eb296862da889609a84f8e10b299b7442d/*"
    args:
      chdir: /tmp/bluez-5.41/

  - name: Bluez: configure
    shell: "/tmp/bluez-5.41/configure --prefix=/usr --mandir=/usr/share/man --sysconfdir=/etc --localstatedir=/var --enable-experimental --enable-tools --with-systemdsystemunitdir=/lib/systemd/system --with-systemduserunitdir=/usr/lib/systemd"

  - name: Bluez: make
    make:
      chdir: /tmp/bluez-5.41/

  - name: Bluez: make install
    make:
      chdir: /tmp/bluez-5.41/
      target: install
#      become: yes


