---
  - name: Install vpnc IPsec client
    apt:
      name: vpnc
      update_cache: yes

  - name: Add the vpnc@.service definition file
    get_url:
      url: "{{vpnc_client_service}}"
      dest: "/lib/systemd/system/vpnc@.service"
      force: yes

  - name: Configure "IPSec gateway" in /etc/vpnc/myvpn.conf
    lineinfile:
      dest: /etc/vpnc/myvpn.conf
      line: IPSec gateway "{{ipsec_gateway}}"
      state: present
      create: yes

  - name: Configure "IPSec ID" in /etc/vpnc/myvpn.conf
    lineinfile:
      dest: /etc/vpnc/myvpn.conf
      line: IPSec ID "{{ipsec_id}}"
      state: present
      create: yes

  - name: Configure "IPSec secret" in /etc/vpnc/myvpn.conf
    lineinfile:
      dest: /etc/vpnc/myvpn.conf
      line: IPSec secret "{{ipsec_secret}}"
      state: present
      create: yes

  - name: Configure "IPSec Xauth username" in /etc/vpnc/myvpn.conf
    lineinfile:
      dest: /etc/vpnc/myvpn.conf
      line: Xauth username "{{ipsec_xauth_username}}"
      state: present
      create: yes

  - name: Configure "IPSec Xauth password" in /etc/vpnc/myvpn.conf
    lineinfile:
      dest: /etc/vpnc/myvpn.conf
      line: Xauth password "{{ipsec_xauth_password}}"
      state: present
      create: yes

  - name: Start the vpnc service
    systemd: 
      name: vpnc@myvpn.service
      state: started
      enabled: yes

  - name: Route Wifi hotspot traffic through tun0 vpn connection in iptables (1 of 3)
    shell: iptables --table nat --append POSTROUTING --out-interface tun0 --jump MASQUERADE
  - name: Route Wifi hotspot traffic through tun0 vpn connection in iptables (2 of 3)
    shell: iptables --append FORWARD --in-interface tun0 --out-interface wlan0 --match state --state RELATED,ESTABLISHED --jump ACCEPT
  - name: Route Wifi hotspot traffic through tun0 vpn connection in iptables (3 of 3)
    shell: iptables --append FORWARD --in-interface wlan0 --out-interface tun0 --jump ACCEPT

  - name: Export iptables
    shell: iptables-save > /etc/iptables.ipv4.nat

  - name: Enable ipv4 forward in /etc/sysctl.conf
    lineinfile:
      dest: /etc/sysctl.conf
      line: 'net.ipv4.ip_forward=1'

  - name: Enable ipv4 forward in /proc/sys/net/ipv4/ip_forward
    shell: echo 1 > /proc/sys/net/ipv4/ip_forward

  - name: Load the iptables NAT config on boot
    lineinfile:
      dest: /etc/rc.local
      line: 'iptables-restore < /etc/iptables.ipv4.nat'
      insertbefore: 'exit 0'
