---
#  - name: Disable IPv6 - set config
#    lineinfile:
#      dest: /etc/sysctl.d/99-sysctl.conf
#    with_items:
#      - "net.ipv6.conf.all.disable_ipv6 = 1"
#      - "net.ipv6.conf.default.disable_ipv6 = 1"
#      - "net.ipv6.conf.lo.disable_ipv6 = 1"

  - name: Disable IPv6 and reload sysctl
    sysctl:
      name: "{{item}}"
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
    with_items:
      - net.ipv6.conf.all.disable_ipv6
      - net.ipv6.conf.default.disable_ipv6
      - net.ipv6.conf.lo.disable_ipv6

  - name: Create user and add to groups
    user:
      name: "{{username}}"
      groups: "{{usergroups}}"
      password: "{{password}}"
      shell: /bin/bash

  - name: Import the sshkey for the new user
    authorized_key:
      user: "{{username}}"
      state: present
      key: "{{sshkey}}"

  - name: Disable using passwords for SSH
    lineinfile: dest=/etc/ssh/sshd_config line='PasswordAuthentication no' state=present

  - name: Disable SSH login for root
    lineinfile: dest=/etc/ssh/sshd_config line='PermitRootLogin no' state=present

  - name: Restarting the SSH service
    service: name=ssh state=restarted

  - name: Install fail2ban
    apt: name=fail2ban state=present

  - name: Set the locale to en_US UTF8
    lineinfile: dest=/etc/locale.gen line='en_US.UTF-8 UTF-8' state=present

  - name: Generate the locale for en_US UTF8
    shell: locale-gen

  - name: Set timezone to "{{timezone}}"
    timezone: name="{{timezone}}"

  - name: Set the hostname
    hostname: name="{{hostname}}"

  - name: Set hostname in /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '^127.0.1.1'
      line: '127.0.1.1  {{hostname}}'

  - name: Remove the user 'pi'
    user: name=pi state=absent remove=yes
    register: command_result
    failed_when: "command_result|failed and 'user pi is currently used' not in command_result.msg"
    ignore_errors: yes
    
  - name: Install basic tools (dnsutils)
    apt:
      name: "{{item}}"
      update_cache: yes
    with_items:
      - dnsutils
