---
  - name: Clone webcam stream docker repository
    git:
      repo: https://github.com/mkieboom/raspberrypi-webcam-stream-docker
      dest: ~/raspberrypi-webcam-stream-docker/

  - name: Build the Docker image
    docker_image:
      path: ~/raspberrypi-webcam-stream-docker/
      name: mkieboom/raspberrypi-webcam-stream-docker

  - name: Launch the webcam stream docker container
    shell: docker run -d --restart=always --name=raspberrypi-webcam-stream-docker -v /tmp/webcam:/input -e MAPR_USER=mapr -e MAPR_PASSWORD=mapr -e MAPR_KAFKA_REST_HOST=MAPRN01 -e MAPR_STREAM=imageclassification-stream -e MAPR_STREAM_TOPIC=webcam-image-events mkieboom/raspberrypi-webcam-stream-docker
