---
  - name: Install vnc server service
    apt:
      name: "{{item}}"
    with_items:
      - realvnc-vnc-server

   # Launch vnc server service
   - name: Start the vnc server service
     service:
       name: vncserver-x11-serviced
       state: restarted
       enabled: yes
