---
  # - name: Check if Docker is already installed
  #   package:
  #     name: docker*
  #     state: present
  #   check_mode: true
  #   register: docker_check

  # - name: Download Docker install script
  #   get_url:
  #     url: http://get.docker.com
  #     dest: /tmp/ansible_docker_install.sh
  #     mode: 0750
  #   when: docker_check.changed 

  # - name: Install Docker
  #   shell: /tmp/ansible_docker_install.sh >> ansible_docker_install.log
  #   when: docker_check.changed 

  #- name: Install Docker gpg key
  #  apt_key:
  #    url: https://download.docker.com/linux/raspbian/gpg
  #    state: present
  #    validate_certs: no

  #- name: Download Docker gpg key
  #  get_url:
  #    url: https://download.docker.com/linux/raspbian/gpg
  #    dest: /tmp/gpg

  - name: Install Docker gpg key
    shell: curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | sudo apt-key add -

  - name: Install Docker repo
    shell: echo "deb [arch=armhf] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) edge" | sudo tee /etc/apt/sources.list.d/docker.list

  # Below Docker install doesn't work on the Pi as there are 2 bugs:
  #
  # We need to install an older version of Docker as the latest version throws following error:
  # "cgroups: memory cgroup not supported on this system"
  # Source: https://github.com/moby/moby/issues/35587
  #
  # Issue with python-requests package version > 2.11.1
  #
  - name: Install Docker-CE and Docker Compose
    apt:
      name: "{{item}}"
      update_cache: yes
    with_items:
      - docker-ce=17.09.0~ce-0~raspbian
      - docker-compose

  - name: Make user 'root' part of the 'docker' group
    user:
      name: root
      groups: docker
      append: yes

  - name: Make user '{{username}}' part of the 'docker' group
    user:
      name: "{{username}}"
      groups: docker
      append: yes
