---
  #- name: Download and install Docker
  #  shell: curl -sSL get.docker.com | sh >> ansible_docker_install.log

  #- name: Download Docker install script
  #  get_url:
  #    url: http://get.docker.com
  #    dest: /tmp/ansible_docker_install.sh
  #    mode: 0750

  #- name: Install Docker
  #  shell: /tmp/ansible_docker_install.sh >> ansible_docker_install.log


# python requests
#http://pypi.python.org/packages/2e/ad/e627446492cc374c284e82381215dcd9a0a87c4f6e90e9789afefe6da0ad/requests-2.11.1.tar.gz

  # Below Docker install doesn't work on the Pi as there are 2 bugs:
  #
  # We need to install an older version of Docker as the latest version throws following error:
  # "cgroups: memory cgroup not supported on this system"
  # Source: https://github.com/moby/moby/issues/35587
  #
  # Issue with python-requests package version > 2.11.1
  #
  - name: Install Docker 
    apt:
      name: "{{item}}"
    with_items:
      - docker-ce=17.09.0~ce-0~raspbian
      - docker-compose

  - name: Make user 'root' part of the 'docker' group
    user:
      name: root
      groups: docker
      append: yes

  - name: Make user '{{username}}' part of the 'docker' group
    user:
      name: "{{username}}"
      groups: docker
      append: yes
